import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GoogleMap, MarkerF, useLoadScript } from '@react-google-maps/api'
import { useEffect, useMemo, useState } from 'react'


export default function Home() {
  const [position, setPosition] = useState({})
  const [trashCanData, setTrashCanData] = useState([]);

  const { isLoaded, loadError } = useLoadScript({ googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAP_API_KEY })
  // console.log(isLoaded, loadError)

  const getTrachCanData = async () => {
    const res = await fetch('/api/hello')
    const data = await res.json()
    setTrashCanData(data)
  }

  useEffect(() => {
    if (navigator) {
      navigator.geolocation.getCurrentPosition(function (position) {
        const newPosition = { lat: position.coords.latitude, lng: position.coords.longitude }
        setPosition(newPosition)
        console.log(newPosition)
      })
    }
    getTrachCanData()
  }, [])

  const center = useMemo(() => (position), [position])
  if (loadError) return <div>Cannot load google map</div>
  if (!isLoaded) return <div>Loading...</div>
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>台北垃圾桶</h2>
        <GoogleMap
          zoom={17}
          center={center}
          mapContainerStyle={{ width: '100%', height: '60vh' }}
        >
          {trashCanData.map(pin => <MarkerF key={pin.緯度 + pin.經度} position={{ lat: Number(pin.緯度), lng: Number(pin.經度) }} />)}
          <MarkerF
            position={position}
          />
        </GoogleMap>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
